version: 2
sphinx:
  configuration: source/conf.py
formats:
  - pdf
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
